import { BaseTimezone } from './types.js';

export const baseTimezones: BaseTimezone[] = [
    { id: 'UTC-12-baker', offset: -12, gmt: 'UTC-12', region: 'Oceania' },
    { id: 'UTC-11-pago-pago', offset: -11, gmt: 'UTC-11', region: 'Pacific' },
    { id: 'UTC-11-niue', offset: -11, gmt: 'UTC-11', region: 'Pacific' },
    { id: 'UTC-10-honolulu', offset: -10, gmt: 'UTC-10', region: 'North America' },
    { id: 'UTC-10-rarotonga', offset: -10, gmt: 'UTC-10', region: 'Pacific' },
    { id: 'UTC-10-papeete', offset: -10, gmt: 'UTC-10', region: 'Pacific' },
    { id: 'UTC-9.5-marquesas', offset: -9.5, gmt: 'UTC-09:30', region: 'Pacific' },
    { id: 'UTC-9-anchorage', offset: -9, gmt: 'UTC-9', region: 'North America' },
    { id: 'UTC-9-gambier', offset: -9, gmt: 'UTC-9', region: 'Pacific' },
    { id: 'UTC-8-los-angeles', offset: -8, gmt: 'UTC-8', region: 'North America' },
    { id: 'UTC-8-vancouver', offset: -8, gmt: 'UTC-8', region: 'North America' },
    { id: 'UTC-8-pitcairn', offset: -8, gmt: 'UTC-8', region: 'Pacific' },
    { id: 'UTC-7-denver', offset: -7, gmt: 'UTC-7', region: 'North America' },
    { id: 'UTC-7-phoenix', offset: -7, gmt: 'UTC-7', region: 'North America' },
    { id: 'UTC-7-edmonton', offset: -7, gmt: 'UTC-7', region: 'North America' },
    { id: 'UTC-6-chicago', offset: -6, gmt: 'UTC-6', region: 'North America' },
    { id: 'UTC-6-mexico-city', offset: -6, gmt: 'UTC-6', region: 'North America' },
    { id: 'UTC-6-guatemala', offset: -6, gmt: 'UTC-6', region: 'Central America' },
    { id: 'UTC-6-san-jose', offset: -6, gmt: 'UTC-6', region: 'Central America' },
    { id: 'UTC-5-new-york', offset: -5, gmt: 'UTC-5', region: 'North America' },
    { id: 'UTC-5-toronto', offset: -5, gmt: 'UTC-5', region: 'North America' },
    { id: 'UTC-5-bogota', offset: -5, gmt: 'UTC-5', region: 'South America' },
    { id: 'UTC-5-lima', offset: -5, gmt: 'UTC-5', region: 'South America' },
    { id: 'UTC-5-panama', offset: -5, gmt: 'UTC-5', region: 'Central America' },
    { id: 'UTC-5-havana', offset: -5, gmt: 'UTC-5', region: 'Caribbean' },
    { id: 'UTC-4-caracas', offset: -4, gmt: 'UTC-4', region: 'South America' },
    { id: 'UTC-4-santiago', offset: -4, gmt: 'UTC-4', region: 'South America' },
    { id: 'UTC-4-la-paz', offset: -4, gmt: 'UTC-4', region: 'South America' },
    { id: 'UTC-4-santo-domingo', offset: -4, gmt: 'UTC-4', region: 'Caribbean' },
    { id: 'UTC-4-halifax', offset: -4, gmt: 'UTC-4', region: 'North America' },
    { id: 'UTC-3.5-st-johns', offset: -3.5, gmt: 'UTC-03:30', region: 'North America' },
    { id: 'UTC-3-buenos-aires', offset: -3, gmt: 'UTC-3', region: 'South America' },
    { id: 'UTC-3-sao-paulo', offset: -3, gmt: 'UTC-3', region: 'South America' },
    { id: 'UTC-3-montevideo', offset: -3, gmt: 'UTC-3', region: 'South America' },
    { id: 'UTC-3-nuuk', offset: -3, gmt: 'UTC-3', region: 'North America' },
    { id: 'UTC-2-noronha', offset: -2, gmt: 'UTC-2', region: 'South America' },
    { id: 'UTC-2-south-georgia', offset: -2, gmt: 'UTC-2', region: 'Atlantic' },
    { id: 'UTC-1-praia', offset: -1, gmt: 'UTC-1', region: 'Africa' },
    { id: 'UTC-1-azores', offset: -1, gmt: 'UTC-1', region: 'Europe' },
    { id: 'UTC+0-london', offset: 0, gmt: 'UTC+0', region: 'Europe' },
    { id: 'UTC+0-dublin', offset: 0, gmt: 'UTC+0', region: 'Europe' },
    { id: 'UTC+0-lisbon', offset: 0, gmt: 'UTC+0', region: 'Europe' },/////
    { id: 'UTC+0-reykjavik', offset: 0, gmt: 'UTC+0', region: 'Europe' },
    { id: 'UTC+0-casablanca', offset: 0, gmt: 'UTC+0', region: 'Africa' },
    { id: 'UTC+0-accra', offset: 0, gmt: 'UTC+0', region: 'Africa' },
    { id: 'UTC+1-paris', offset: 1, gmt: 'UTC+1', region: 'Europe' },
    { id: 'UTC+1-berlin', offset: 1, gmt: 'UTC+1', region: 'Europe' },
    { id: 'UTC+1-rome', offset: 1, gmt: 'UTC+1', region: 'Europe' },
    { id: 'UTC+1-madrid', offset: 1, gmt: 'UTC+1', region: 'Europe' },
    { id: 'UTC+1-amsterdam', offset: 1, gmt: 'UTC+1', region: 'Europe' },
    { id: 'UTC+1-lagos', offset: 1, gmt: 'UTC+1', region: 'Africa' },
    { id: 'UTC+1-tunis', offset: 1, gmt: 'UTC+1', region: 'Africa' },
    { id: 'UTC+2-athens', offset: 2, gmt: 'UTC+2', region: 'Europe' },
    { id: 'UTC+2-helsinki', offset: 2, gmt: 'UTC+2', region: 'Europe' },
    { id: 'UTC+2-bucharest', offset: 2, gmt: 'UTC+2', region: 'Europe' },
    { id: 'UTC+2-kyiv', offset: 2, gmt: 'UTC+2', region: 'Europe' },
    { id: 'UTC+2-cairo', offset: 2, gmt: 'UTC+2', region: 'Africa' },
    { id: 'UTC+2-johannesburg', offset: 2, gmt: 'UTC+2', region: 'Africa' },
    { id: 'UTC+2-jerusalem', offset: 2, gmt: 'UTC+2', region: 'Asia' },
    { id: 'UTC+2-beirut', offset: 2, gmt: 'UTC+2', region: 'Asia' },
    { id: 'UTC+3-istanbul', offset: 3, gmt: 'UTC+3', region: 'Europe/Asia' },
    { id: 'UTC+3-moscow', offset: 3, gmt: 'UTC+3', region: 'Europe' },
    { id: 'UTC+3-riyadh', offset: 3, gmt: 'UTC+3', region: 'Asia' },
    { id: 'UTC+3-baghdad', offset: 3, gmt: 'UTC+3', region: 'Asia' },
    { id: 'UTC+3-doha', offset: 3, gmt: 'UTC+3', region: 'Asia' },
    { id: 'UTC+3-amman', offset: 3, gmt: 'UTC+3', region: 'Asia' },
    { id: 'UTC+3-damascus', offset: 3, gmt: 'UTC+3', region: 'Asia' },
    { id: 'UTC+3-nairobi', offset: 3, gmt: 'UTC+3', region: 'Africa' },
    { id: 'UTC+3-addis-ababa', offset: 3, gmt: 'UTC+3', region: 'Africa' },
    { id: 'UTC+3.5-tehran', offset: 3.5, gmt: 'UTC+03:30', region: 'Asia' },
    { id: 'UTC+4-dubai', offset: 4, gmt: 'UTC+4', region: 'Asia' },
    { id: 'UTC+4-baku', offset: 4, gmt: 'UTC+4', region: 'Asia' },
    { id: 'UTC+4-tbilisi', offset: 4, gmt: 'UTC+4', region: 'Asia' },
    { id: 'UTC+4-yerevan', offset: 4, gmt: 'UTC+4', region: 'Asia' },
    { id: 'UTC+4-port-louis', offset: 4, gmt: 'UTC+4', region: 'Africa' },
    { id: 'UTC+4.5-kabul', offset: 4.5, gmt: 'UTC+04:30', region: 'Asia' },
    { id: 'UTC+5-karachi', offset: 5, gmt: 'UTC+5', region: 'Asia' },
    { id: 'UTC+5-tashkent', offset: 5, gmt: 'UTC+5', region: 'Asia' },
    { id: 'UTC+5-ashgabat', offset: 5, gmt: 'UTC+5', region: 'Asia' },
    { id: 'UTC+5-male', offset: 5, gmt: 'UTC+5', region: 'Asia' },
    { id: 'UTC+5.5-colombo', offset: 5.5, gmt: 'UTC+05:30', region: 'Asia' },
    { id: 'UTC+5.5-mumbai', offset: 5.5, gmt: 'UTC+05:30', region: 'Asia' },
    { id: 'UTC+5.75-kathmandu', offset: 5.75, gmt: 'UTC+05:45', region: 'Asia' },
    { id: 'UTC+6-dhaka', offset: 6, gmt: 'UTC+6', region: 'Asia' },
    { id: 'UTC+6-almaty', offset: 6, gmt: 'UTC+6', region: 'Asia' },
    { id: 'UTC+6-bishkek', offset: 6, gmt: 'UTC+6', region: 'Asia' },
    { id: 'UTC+6.5-yangon', offset: 6.5, gmt: 'UTC+06:30', region: 'Asia' },
    { id: 'UTC+7-bangkok', offset: 7, gmt: 'UTC+7', region: 'Asia' },
    { id: 'UTC+7-jakarta', offset: 7, gmt: 'UTC+7', region: 'Asia' },
    { id: 'UTC+7-hanoi', offset: 7, gmt: 'UTC+7', region: 'Asia' },
    { id: 'UTC+7-phnom-penh', offset: 7, gmt: 'UTC+7', region: 'Asia' },
    { id: 'UTC+8-beijing', offset: 8, gmt: 'UTC+8', region: 'Asia' },
    { id: 'UTC+8-singapore', offset: 8, gmt: 'UTC+8', region: 'Asia' },
    { id: 'UTC+8-manila', offset: 8, gmt: 'UTC+8', region: 'Asia' },
    { id: 'UTC+8-kuala-lumpur', offset: 8, gmt: 'UTC+8', region: 'Asia' },
    { id: 'UTC+8-taipei', offset: 8, gmt: 'UTC+8', region: 'Asia' },
    { id: 'UTC+8-perth', offset: 8, gmt: 'UTC+8', region: 'Australia' },
    { id: 'UTC+8.75-eucla', offset: 8.75, gmt: 'UTC+08:45', region: 'Australia' },
    { id: 'UTC+9-tokyo', offset: 9, gmt: 'UTC+9', region: 'Asia' },
    { id: 'UTC+9-seoul', offset: 9, gmt: 'UTC+9', region: 'Asia' },
    { id: 'UTC+9-pyongyang', offset: 9, gmt: 'UTC+9', region: 'Asia' },
    { id: 'UTC+9.5-darwin', offset: 9.5, gmt: 'UTC+09:30', region: 'Australia' },
    { id: 'UTC+10-sydney', offset: 10, gmt: 'UTC+10', region: 'Australia' },
    { id: 'UTC+10-melbourne', offset: 10, gmt: 'UTC+10', region: 'Australia' },
    { id: 'UTC+10-vladivostok', offset: 10, gmt: 'UTC+10', region: 'Europe/Asia' },
    { id: 'UTC+10-port-moresby', offset: 10, gmt: 'UTC+10', region: 'Oceania' },
    { id: 'UTC+10.5-lord-howe', offset: 10.5, gmt: 'UTC+10:30', region: 'Australia' },
    { id: 'UTC+11-noumea', offset: 11, gmt: 'UTC+11', region: 'Oceania' },
    { id: 'UTC+11-honiara', offset: 11, gmt: 'UTC+11', region: 'Oceania' },
    { id: 'UTC+12-auckland', offset: 12, gmt: 'UTC+12', region: 'Oceania' },
    { id: 'UTC+12-suva', offset: 12, gmt: 'UTC+12', region: 'Oceania' },
    { id: 'UTC+12.75-chatham', offset: 12.75, gmt: 'UTC+12:45', region: 'Oceania' },
    { id: 'UTC+13-apia', offset: 13, gmt: 'UTC+13', region: 'Pacific' },
    { id: 'UTC+13-nukualofa', offset: 13, gmt: 'UTC+13', region: 'Pacific' },
    { id: 'UTC+14-kiritimati', offset: 14, gmt: 'UTC+14', region: 'Pacific' }
];