import { BaseTimezone } from './types.js';

export const baseTimezones: BaseTimezone[] = [
    { id: 'UTC-12-baker', offset: -12, rawOffset: -43200, gmt: 'UTC-12', abbr: 'BIT', iana: 'Etc/GMT+12', isoCode: 'US', region: 'Oceania', hasDst: false },
    { id: 'UTC-11-pago-pago', offset: -11, rawOffset: -39600, gmt: 'UTC-11', abbr: 'SST', iana: 'Pacific/Pago_Pago', isoCode: 'AS', region: 'Pacific', hasDst: false },
    { id: 'UTC-11-niue', offset: -11, rawOffset: -39600, gmt: 'UTC-11', abbr: 'NUT', iana: 'Pacific/Niue', isoCode: 'NU', region: 'Pacific', hasDst: false },
    { id: 'UTC-10-honolulu', offset: -10, rawOffset: -36000, gmt: 'UTC-10', abbr: 'HST', iana: 'Pacific/Honolulu', isoCode: 'US', region: 'North America', hasDst: false },
    { id: 'UTC-10-rarotonga', offset: -10, rawOffset: -36000, gmt: 'UTC-10', abbr: 'CKT', iana: 'Pacific/Rarotonga', isoCode: 'CK', region: 'Pacific', hasDst: false },
    { id: 'UTC-10-papeete', offset: -10, rawOffset: -36000, gmt: 'UTC-10', abbr: 'TAHT', iana: 'Pacific/Papeete', isoCode: 'PF', region: 'Pacific', hasDst: false },
    { id: 'UTC-9.5-marquesas', offset: -9.5, rawOffset: -34200, gmt: 'UTC-09:30', abbr: 'MART', iana: 'Pacific/Marquesas', isoCode: 'PF', region: 'Pacific', hasDst: false },
    { id: 'UTC-9-anchorage', offset: -9, rawOffset: -32400, gmt: 'UTC-9', abbr: 'AKST', iana: 'America/Anchorage', isoCode: 'US', region: 'North America', hasDst: true },
    { id: 'UTC-9-gambier', offset: -9, rawOffset: -32400, gmt: 'UTC-9', abbr: 'GAMT', iana: 'Pacific/Gambier', isoCode: 'PF', region: 'Pacific', hasDst: false },
    { id: 'UTC-8-los-angeles', offset: -8, rawOffset: -28800, gmt: 'UTC-8', abbr: 'PST', iana: 'America/Los_Angeles', isoCode: 'US', region: 'North America', hasDst: true },
    { id: 'UTC-8-vancouver', offset: -8, rawOffset: -28800, gmt: 'UTC-8', abbr: 'PST', iana: 'America/Vancouver', isoCode: 'CA', region: 'North America', hasDst: true },
    { id: 'UTC-8-pitcairn', offset: -8, rawOffset: -28800, gmt: 'UTC-8', abbr: 'PST', iana: 'Pacific/Pitcairn', isoCode: 'PN', region: 'Pacific', hasDst: false },
    { id: 'UTC-7-denver', offset: -7, rawOffset: -25200, gmt: 'UTC-7', abbr: 'MST', iana: 'America/Denver', isoCode: 'US', region: 'North America', hasDst: true },
    { id: 'UTC-7-phoenix', offset: -7, rawOffset: -25200, gmt: 'UTC-7', abbr: 'MST', iana: 'America/Phoenix', isoCode: 'US', region: 'North America', hasDst: false },
    { id: 'UTC-7-edmonton', offset: -7, rawOffset: -25200, gmt: 'UTC-7', abbr: 'MST', iana: 'America/Edmonton', isoCode: 'CA', region: 'North America', hasDst: true },
    { id: 'UTC-6-chicago', offset: -6, rawOffset: -21600, gmt: 'UTC-6', abbr: 'CST', iana: 'America/Chicago', isoCode: 'US', region: 'North America', hasDst: true },
    { id: 'UTC-6-mexico-city', offset: -6, rawOffset: -21600, gmt: 'UTC-6', abbr: 'CST', iana: 'America/Mexico_City', isoCode: 'MX', region: 'North America', hasDst: false },
    { id: 'UTC-6-guatemala', offset: -6, rawOffset: -21600, gmt: 'UTC-6', abbr: 'CST', iana: 'America/Guatemala', isoCode: 'GT', region: 'Central America', hasDst: false },
    { id: 'UTC-6-san-jose', offset: -6, rawOffset: -21600, gmt: 'UTC-6', abbr: 'CST', iana: 'America/Costa_Rica', isoCode: 'CR', region: 'Central America', hasDst: false },
    { id: 'UTC-5-new-york', offset: -5, rawOffset: -18000, gmt: 'UTC-5', abbr: 'EST', iana: 'America/New_York', isoCode: 'US', region: 'North America', hasDst: true },
    { id: 'UTC-5-toronto', offset: -5, rawOffset: -18000, gmt: 'UTC-5', abbr: 'EST', iana: 'America/Toronto', isoCode: 'CA', region: 'North America', hasDst: true },
    { id: 'UTC-5-bogota', offset: -5, rawOffset: -18000, gmt: 'UTC-5', abbr: 'COT', iana: 'America/Bogota', isoCode: 'CO', region: 'South America', hasDst: false },
    { id: 'UTC-5-lima', offset: -5, rawOffset: -18000, gmt: 'UTC-5', abbr: 'PET', iana: 'America/Lima', isoCode: 'PE', region: 'South America', hasDst: false },
    { id: 'UTC-5-panama', offset: -5, rawOffset: -18000, gmt: 'UTC-5', abbr: 'EST', iana: 'America/Panama', isoCode: 'PA', region: 'Central America', hasDst: false },
    { id: 'UTC-5-havana', offset: -5, rawOffset: -18000, gmt: 'UTC-5', abbr: 'CST', iana: 'America/Havana', isoCode: 'CU', region: 'Caribbean', hasDst: true },
    { id: 'UTC-4-caracas', offset: -4, rawOffset: -14400, gmt: 'UTC-4', abbr: 'VET', iana: 'America/Caracas', isoCode: 'VE', region: 'South America', hasDst: false },
    { id: 'UTC-4-santiago', offset: -4, rawOffset: -14400, gmt: 'UTC-4', abbr: 'CLST', iana: 'America/Santiago', isoCode: 'CL', region: 'South America', hasDst: true },
    { id: 'UTC-4-la-paz', offset: -4, rawOffset: -14400, gmt: 'UTC-4', abbr: 'BOT', iana: 'America/La_Paz', isoCode: 'BO', region: 'South America', hasDst: false },
    { id: 'UTC-4-santo-domingo', offset: -4, rawOffset: -14400, gmt: 'UTC-4', abbr: 'AST', iana: 'America/Santo_Domingo', isoCode: 'DO', region: 'Caribbean', hasDst: false },
    { id: 'UTC-4-halifax', offset: -4, rawOffset: -14400, gmt: 'UTC-4', abbr: 'AST', iana: 'America/Halifax', isoCode: 'CA', region: 'North America', hasDst: true },
    { id: 'UTC-3.5-st-johns', offset: -3.5, rawOffset: -12600, gmt: 'UTC-03:30', abbr: 'NST', iana: 'America/St_Johns', isoCode: 'CA', region: 'North America', hasDst: true },
    { id: 'UTC-3-buenos-aires', offset: -3, rawOffset: -10800, gmt: 'UTC-3', abbr: 'ART', iana: 'America/Argentina/Buenos_Aires', isoCode: 'AR', region: 'South America', hasDst: false },
    { id: 'UTC-3-sao-paulo', offset: -3, rawOffset: -10800, gmt: 'UTC-3', abbr: 'BRT', iana: 'America/Sao_Paulo', isoCode: 'BR', region: 'South America', hasDst: false },
    { id: 'UTC-3-montevideo', offset: -3, rawOffset: -10800, gmt: 'UTC-3', abbr: 'UYT', iana: 'America/Montevideo', isoCode: 'UY', region: 'South America', hasDst: false },
    { id: 'UTC-3-nuuk', offset: -3, rawOffset: -10800, gmt: 'UTC-3', abbr: 'WGT', iana: 'America/Nuuk', isoCode: 'GL', region: 'North America', hasDst: false },
    { id: 'UTC-2-noronha', offset: -2, rawOffset: -7200, gmt: 'UTC-2', abbr: 'FNT', iana: 'America/Noronha', isoCode: 'BR', region: 'South America', hasDst: false },
    { id: 'UTC-2-south-georgia', offset: -2, rawOffset: -7200, gmt: 'UTC-2', abbr: 'GST', iana: 'Atlantic/South_Georgia', isoCode: 'GS', region: 'Atlantic', hasDst: false },
    { id: 'UTC-1-praia', offset: -1, rawOffset: -3600, gmt: 'UTC-1', abbr: 'CVT', iana: 'Atlantic/Cape_Verde', isoCode: 'CV', region: 'Africa', hasDst: false },
    { id: 'UTC-1-azores', offset: -1, rawOffset: -3600, gmt: 'UTC-1', abbr: 'AZOT', iana: 'Atlantic/Azores', isoCode: 'PT', region: 'Europe', hasDst: true },
    { id: 'UTC+0-london', offset: 0, rawOffset: 0, gmt: 'UTC+0', abbr: 'GMT', iana: 'Europe/London', isoCode: 'GB', region: 'Europe', hasDst: true },
    { id: 'UTC+0-dublin', offset: 0, rawOffset: 0, gmt: 'UTC+0', abbr: 'GMT', iana: 'Europe/Dublin', isoCode: 'IE', region: 'Europe', hasDst: true },
    { id: 'UTC+0-lisbon', offset: 0, rawOffset: 0, gmt: 'UTC+0', abbr: 'WET', iana: 'Europe/Lisbon', isoCode: 'PT', region: 'Europe', hasDst: true },
    { id: 'UTC+0-reykjavik', offset: 0, rawOffset: 0, gmt: 'UTC+0', abbr: 'GMT', iana: 'Africa/Abidjan', isoCode: 'IS', region: 'Europe', hasDst: false },
    { id: 'UTC+0-casablanca', offset: 0, rawOffset: 0, gmt: 'UTC+0', abbr: 'WET', iana: 'Africa/Casablanca', isoCode: 'MA', region: 'Africa', hasDst: true },
    { id: 'UTC+0-accra', offset: 0, rawOffset: 0, gmt: 'UTC+0', abbr: 'GMT', iana: 'Africa/Accra', isoCode: 'GH', region: 'Africa', hasDst: false },
    { id: 'UTC+1-paris', offset: 1, rawOffset: 3600, gmt: 'UTC+1', abbr: 'CET', iana: 'Europe/Paris', isoCode: 'FR', region: 'Europe', hasDst: true },
    { id: 'UTC+1-berlin', offset: 1, rawOffset: 3600, gmt: 'UTC+1', abbr: 'CET', iana: 'Europe/Berlin', isoCode: 'DE', region: 'Europe', hasDst: true },
    { id: 'UTC+1-rome', offset: 1, rawOffset: 3600, gmt: 'UTC+1', abbr: 'CET', iana: 'Europe/Rome', isoCode: 'IT', region: 'Europe', hasDst: true },
    { id: 'UTC+1-madrid', offset: 1, rawOffset: 3600, gmt: 'UTC+1', abbr: 'CET', iana: 'Europe/Madrid', isoCode: 'SP', region: 'Europe', hasDst: true },
    { id: 'UTC+1-amsterdam', offset: 1, rawOffset: 3600, gmt: 'UTC+1', abbr: 'CET', iana: 'Europe/Amsterdam', isoCode: 'NL', region: 'Europe', hasDst: true },
    { id: 'UTC+1-lagos', offset: 1, rawOffset: 3600, gmt: 'UTC+1', abbr: 'WAT', iana: 'Africa/Lagos', isoCode: 'NG', region: 'Africa', hasDst: false },
    { id: 'UTC+1-tunis', offset: 1, rawOffset: 3600, gmt: 'UTC+1', abbr: 'WAT', iana: 'Africa/Tunis', isoCode: 'TN', region: 'Africa', hasDst: false },
    { id: 'UTC+2-athens', offset: 2, rawOffset: 7200, gmt: 'UTC+2', abbr: 'EET', iana: 'Europe/Athens', isoCode: 'GR', region: 'Europe', hasDst: true },
    { id: 'UTC+2-helsinki', offset: 2, rawOffset: 7200, gmt: 'UTC+2', abbr: 'EET', iana: 'Europe/Helsinki', isoCode: 'FI', region: 'Europe', hasDst: true },
    { id: 'UTC+2-bucharest', offset: 2, rawOffset: 7200, gmt: 'UTC+2', abbr: 'EET', iana: 'Europe/Bucharest', isoCode: 'RO', region: 'Europe', hasDst: true },
    { id: 'UTC+2-kyiv', offset: 2, rawOffset: 7200, gmt: 'UTC+2', abbr: 'EET', iana: 'Europe/Kyiv', isoCode: 'UA', region: 'Europe', hasDst: true },
    { id: 'UTC+2-cairo', offset: 2, rawOffset: 7200, gmt: 'UTC+2', abbr: 'EET', iana: 'Africa/Cairo', isoCode: 'EG', region: 'Africa', hasDst: true },
    { id: 'UTC+2-johannesburg', offset: 2, rawOffset: 7200, gmt: 'UTC+2', abbr: 'SAST', iana: 'Africa/Johannesburg', isoCode: 'ZA', region: 'Africa', hasDst: false },
    { id: 'UTC+2-jerusalem', offset: 2, rawOffset: 7200, gmt: 'UTC+2', abbr: 'IST', iana: 'Asia/Jerusalem', isoCode: 'IL', region: 'Asia', hasDst: true },
    { id: 'UTC+2-beirut', offset: 2, rawOffset: 7200, gmt: 'UTC+2', abbr: 'EET', iana: 'Asia/Beirut', isoCode: 'LB', region: 'Asia', hasDst: true },
    { id: 'UTC+3-istanbul', offset: 3, rawOffset: 10800, gmt: 'UTC+3', abbr: 'TRT', iana: 'Europe/Istanbul', isoCode: 'TR', region: 'Europe/Asia', hasDst: false },
    { id: 'UTC+3-moscow', offset: 3, rawOffset: 10800, gmt: 'UTC+3', abbr: 'MSK', iana: 'Europe/Moscow', isoCode: 'RU', region: 'Europe', hasDst: false },
    { id: 'UTC+3-riyadh', offset: 3, rawOffset: 10800, gmt: 'UTC+3', abbr: 'AST', iana: 'Asia/Riyadh', isoCode: 'SA', region: 'Asia', hasDst: false },
    { id: 'UTC+3-baghdad', offset: 3, rawOffset: 10800, gmt: 'UTC+3', abbr: 'AST', iana: 'Asia/Baghdad', isoCode: 'IQ', region: 'Asia', hasDst: false },
    { id: 'UTC+3-doha', offset: 3, rawOffset: 10800, gmt: 'UTC+3', abbr: 'AST', iana: 'Asia/Qatar', isoCode: 'QA', region: 'Asia', hasDst: false },
    { id: 'UTC+3-amman', offset: 3, rawOffset: 10800, gmt: 'UTC+3', abbr: 'AST', iana: 'Asia/Amman', isoCode: 'JO', region: 'Asia', hasDst: false },
    { id: 'UTC+3-damascus', offset: 3, rawOffset: 10800, gmt: 'UTC+3', abbr: 'AST', iana: 'Asia/Damascus', isoCode: 'SY', region: 'Asia', hasDst: false },
    { id: 'UTC+3-nairobi', offset: 3, rawOffset: 10800, gmt: 'UTC+3', abbr: 'EAT', iana: 'Africa/Nairobi', isoCode: 'KE', region: 'Africa', hasDst: false },
    { id: 'UTC+3-addis-ababa', offset: 3, rawOffset: 10800, gmt: 'UTC+3', abbr: 'EAT', iana: 'Africa/Addis_Ababa', isoCode: 'ET', region: 'Africa', hasDst: false },
    { id: 'UTC+3.5-tehran', offset: 3.5, rawOffset: 12600, gmt: 'UTC+03:30', abbr: 'IRST', iana: 'Asia/Tehran', isoCode: 'IR', region: 'Asia', hasDst: false },
    { id: 'UTC+4-dubai', offset: 4, rawOffset: 14400, gmt: 'UTC+4', abbr: 'GST', iana: 'Asia/Dubai', isoCode: 'AE', region: 'Asia', hasDst: false },
    { id: 'UTC+4-baku', offset: 4, rawOffset: 14400, gmt: 'UTC+4', abbr: 'AZT', iana: 'Asia/Baku', isoCode: 'AZ', region: 'Asia', hasDst: false },
    { id: 'UTC+4-tbilisi', offset: 4, rawOffset: 14400, gmt: 'UTC+4', abbr: 'GET', iana: 'Asia/Tbilisi', isoCode: 'GE', region: 'Asia', hasDst: false },
    { id: 'UTC+4-yerevan', offset: 4, rawOffset: 14400, gmt: 'UTC+4', abbr: 'AMT', iana: 'Asia/Yerevan', isoCode: 'AM', region: 'Asia', hasDst: false },
    { id: 'UTC+4-port-louis', offset: 4, rawOffset: 14400, gmt: 'UTC+4', abbr: 'MUT', iana: 'Indian/Mauritius', isoCode: 'MU', region: 'Africa', hasDst: false },
    { id: 'UTC+4.5-kabul', offset: 4.5, rawOffset: 16200, gmt: 'UTC+04:30', abbr: 'AFT', iana: 'Asia/Kabul', isoCode: 'AF', region: 'Asia', hasDst: false },
    { id: 'UTC+5-karachi', offset: 5, rawOffset: 18000, gmt: 'UTC+5', abbr: 'PKT', iana: 'Asia/Karachi', isoCode: 'PK', region: 'Asia', hasDst: false },
    { id: 'UTC+5-tashkent', offset: 5, rawOffset: 18000, gmt: 'UTC+5', abbr: 'UZT', iana: 'Asia/Tashkent', isoCode: 'UZ', region: 'Asia', hasDst: false },
    { id: 'UTC+5-ashgabat', offset: 5, rawOffset: 18000, gmt: 'UTC+5', abbr: 'TMT', iana: 'Asia/Ashgabat', isoCode: 'TM', region: 'Asia', hasDst: false },
    { id: 'UTC+5-male', offset: 5, rawOffset: 18000, gmt: 'UTC+5', abbr: 'MVT', iana: 'Indian/Maldives', isoCode: 'MV', region: 'Asia', hasDst: false },
    { id: 'UTC+5.5-colombo', offset: 5.5, rawOffset: 19800, gmt: 'UTC+05:30', abbr: 'IST', iana: 'Asia/Colombo', isoCode: 'LK', region: 'Asia', hasDst: false },
    { id: 'UTC+5.5-mumbai', offset: 5.5, rawOffset: 19800, gmt: 'UTC+05:30', abbr: 'IST', iana: 'Asia/Kolkata', isoCode: 'IN', region: 'Asia', hasDst: false },
    { id: 'UTC+5.75-kathmandu', offset: 5.75, rawOffset: 20700, gmt: 'UTC+05:45', abbr: 'NPT', iana: 'Asia/Kathmandu', isoCode: 'NP', region: 'Asia', hasDst: false },
    { id: 'UTC+6-dhaka', offset: 6, rawOffset: 21600, gmt: 'UTC+6', abbr: 'BST', iana: 'Asia/Dhaka', isoCode: 'BD', region: 'Asia', hasDst: false },
    { id: 'UTC+6-almaty', offset: 6, rawOffset: 21600, gmt: 'UTC+6', abbr: 'ALMT', iana: 'Asia/Almaty', isoCode: 'KZ', region: 'Asia', hasDst: false },
    { id: 'UTC+6-bishkek', offset: 6, rawOffset: 21600, gmt: 'UTC+6', abbr: 'KGT', iana: 'Asia/Bishkek', isoCode: 'KG', region: 'Asia', hasDst: false },
    { id: 'UTC+6.5-yangon', offset: 6.5, rawOffset: 23400, gmt: 'UTC+06:30', abbr: 'MMT', iana: 'Asia/Yangon', isoCode: 'MM', region: 'Asia', hasDst: false },
    { id: 'UTC+7-bangkok', offset: 7, rawOffset: 25200, gmt: 'UTC+7', abbr: 'ICT', iana: 'Asia/Bangkok', isoCode: 'TH', region: 'Asia', hasDst: false },
    { id: 'UTC+7-jakarta', offset: 7, rawOffset: 25200, gmt: 'UTC+7', abbr: 'WIB', iana: 'Asia/Jakarta', isoCode: 'ID', region: 'Asia', hasDst: false },
    { id: 'UTC+7-hanoi', offset: 7, rawOffset: 25200, gmt: 'UTC+7', abbr: 'ICT', iana: 'Asia/Ho_Chi_Minh', isoCode: 'VN', region: 'Asia', hasDst: false },
    { id: 'UTC+7-phnom-penh', offset: 7, rawOffset: 25200, gmt: 'UTC+7', abbr: 'ICT', iana: 'Asia/Phnom_Penh', isoCode: 'KH', region: 'Asia', hasDst: false },
    { id: 'UTC+8-beijing', offset: 8, rawOffset: 28800, gmt: 'UTC+8', abbr: 'CST', iana: 'Asia/Shanghai', isoCode: 'CN', region: 'Asia', hasDst: false },
    { id: 'UTC+8-singapore', offset: 8, rawOffset: 28800, gmt: 'UTC+8', abbr: 'SGT', iana: 'Asia/Singapore', isoCode: 'SG', region: 'Asia', hasDst: false },
    { id: 'UTC+8-manila', offset: 8, rawOffset: 28800, gmt: 'UTC+8', abbr: 'PHT', iana: 'Asia/Manila', isoCode: 'PH', region: 'Asia', hasDst: false },
    { id: 'UTC+8-kuala-lumpur', offset: 8, rawOffset: 28800, gmt: 'UTC+8', abbr: 'MYT', iana: 'Asia/Kuala_Lumpur', isoCode: 'MY', region: 'Asia', hasDst: false },
    { id: 'UTC+8-taipei', offset: 8, rawOffset: 28800, gmt: 'UTC+8', abbr: 'CST', iana: 'Asia/Taipei', isoCode: 'TW', region: 'Asia', hasDst: false },
    { id: 'UTC+8-perth', offset: 8, rawOffset: 28800, gmt: 'UTC+8', abbr: 'AWST', iana: 'Australia/Perth', isoCode: 'AU', region: 'Australia', hasDst: false },
    { id: 'UTC+8.75-eucla', offset: 8.75, rawOffset: 31500, gmt: 'UTC+08:45', abbr: 'ACWST', iana: 'Australia/Eucla', isoCode: 'AU', region: 'Australia', hasDst: false },
    { id: 'UTC+9-tokyo', offset: 9, rawOffset: 32400, gmt: 'UTC+9', abbr: 'JST', iana: 'Asia/Tokyo', isoCode: 'JP', region: 'Asia', hasDst: false },
    { id: 'UTC+9-seoul', offset: 9, rawOffset: 32400, gmt: 'UTC+9', abbr: 'KST', iana: 'Asia/Seoul', isoCode: 'KR', region: 'Asia', hasDst: false },
    { id: 'UTC+9-pyongyang', offset: 9, rawOffset: 32400, gmt: 'UTC+9', abbr: 'KST', iana: 'Asia/Pyongyang', isoCode: 'KP', region: 'Asia', hasDst: false },
    { id: 'UTC+9.5-darwin', offset: 9.5, rawOffset: 34200, gmt: 'UTC+09:30', abbr: 'ACST', iana: 'Australia/Darwin', isoCode: 'AU', region: 'Australia', hasDst: false },
    { id: 'UTC+10-sydney', offset: 10, rawOffset: 36000, gmt: 'UTC+10', abbr: 'AEST', iana: 'Australia/Sydney', isoCode: 'AU', region: 'Australia', hasDst: true },
    { id: 'UTC+10-melbourne', offset: 10, rawOffset: 36000, gmt: 'UTC+10', abbr: 'AEST', iana: 'Australia/Melbourne', isoCode: 'AU', region: 'Australia', hasDst: true },
    { id: 'UTC+10-vladivostok', offset: 10, rawOffset: 36000, gmt: 'UTC+10', abbr: 'VLAT', iana: 'Asia/Vladivostok', isoCode: 'RU', region: 'Asia', hasDst: false },
    { id: 'UTC+10-port-moresby', offset: 10, rawOffset: 36000, gmt: 'UTC+10', abbr: 'PGT', iana: 'Pacific/Port_Moresby', isoCode: 'PG', region: 'Oceania', hasDst: false },
    { id: 'UTC+10.5-lord-howe', offset: 10.5, rawOffset: 37800, gmt: 'UTC+10:30', abbr: 'LHST', iana: 'Australia/Lord_Howe', isoCode: 'AU', region: 'Australia', hasDst: true },
    { id: 'UTC+11-noumea', offset: 11, rawOffset: 39600, gmt: 'UTC+11', abbr: 'SCT', iana: 'Pacific/Noumea', isoCode: 'NC', region: 'New Caledonia', hasDst: false },
    { id: 'UTC+11-honiara', offset: 11, rawOffset: 39600, gmt: 'UTC+11', abbr: 'SBT', iana: 'Pacific/Honiara', isoCode: 'SB', region: 'Solomon Islands', hasDst: false },
    { id: 'UTC+12-auckland', offset: 12, rawOffset: 43200, gmt: 'UTC+12', abbr: 'NZST', iana: 'Pacific/Auckland', isoCode: 'NZ', region: 'Oceania', hasDst: true },
    { id: 'UTC+12-suva', offset: 12, rawOffset: 43200, gmt: 'UTC+12', abbr: 'FJT', iana: 'Pacific/Suva', isoCode: 'FJ', region: 'Fiji', hasDst: false },
    { id: 'UTC+12.75-chatham', offset: 12.75, rawOffset: 45900, gmt: 'UTC+12:45', abbr: 'CHAST', iana: 'Pacific/Chatham', isoCode: 'NZ', region: 'Oceania', hasDst: true },
    { id: 'UTC+13-apia', offset: 13, rawOffset: 46800, gmt: 'UTC+13', abbr: 'WST', iana: 'Pacific/Apia', isoCode: 'WS', region: 'Pacific', hasDst: false },
    { id: 'UTC+13-nukualofa', offset: 13, rawOffset: 46800, gmt: 'UTC+13', abbr: 'TOT', iana: 'Pacific/Tongatapu', isoCode: 'TO', region: 'Tonga', hasDst: false },
    { id: 'UTC+14-kiritimati', offset: 14, rawOffset: 50400, gmt: 'UTC+14', abbr: 'LINT', iana: 'Pacific/Kiritimati', isoCode: 'KI', region: 'Pacific', hasDst: false }
];